### ISSUE TITLE
Throws error if the source files doesn't exist

### ISSUE THREAD

**Issue by jamesgeorge007** [imba/imba#195]
Supplying a directory that doesn't exist as an argument with `imba` or a file that doesn't exist with `imbac` results in an error as below:-
> imba

```
fs.js:948
  binding.stat(pathModule._makeLong(path));
          ^

Error: ENOENT: no such file or directory, stat '/home/james-the-hacker/a'
    at Object.fs.statSync (fs.js:948:11)
    at Object.self.lookup (/home/james-the-hacker/CodeSpace/GitHub-Projects/imba/lib/cli/imba.js:20:9)
    at Object.exports.run.self.run (/home/james-the-hacker/CodeSpace/GitHub-Projects/imba/lib/cli/imba.js:60:13)
    at Object.<anonymous> (/home/james-the-hacker/CodeSpace/GitHub-Projects/imba/bin/imba:6:28)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
```
> imbac

```
fs.js:948
  binding.stat(pathModule._makeLong(path));
          ^

Error: ENOENT: no such file or directory, stat '/home/james-the-hacker/a'
    at Object.fs.statSync (fs.js:948:11)
    at CLI.pathToSource (/home/james-the-hacker/CodeSpace/GitHub-Projects/imba/lib/cli/imbac.js:106:16)
    at CLI.run (/home/james-the-hacker/CodeSpace/GitHub-Projects/imba/lib/cli/imbac.js:152:8)
    at Object.exports.run.self.run (/home/james-the-hacker/CodeSpace/GitHub-Projects/imba/lib/cli/imbac.js:408:21)
    at Object.<anonymous> (/home/james-the-hacker/CodeSpace/GitHub-Projects/imba/bin/imbac:6:29)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

I think it's good to have a custom message showing up in this scenario instead :thinking:

**Comment by jamesgeorge007** [comment]
@somebee Thoughts?

**Comment by athif23** [comment]
We just need to wait for imba to be refactored/rewrote to be cleaner and tidier. But, unfortunately, it will take many times.
