### ISSUE TITLE
Lowercase classes are not allowed

### ISSUE THREAD

**Issue by scanf** [imba/imba#224]
The following snippet will not work in Imba and results in an error due to the lowercase class name `x1`. It would nice for quick prototyping to not force casing on the class names. 

```
const x = new self.x1();
          ^

TypeError: self.x1 is not a constructor
    at Object.<anonymous> (/private/tmp/x.imba:6:11)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.exports.run.self.run (/Users/ccscanf/.nvm/versions/node/v10.16.0/lib/node_modules/imba/lib/compiler/index.js:48:15)
    at Object.exports.run.self.run (/Users/ccscanf/.nvm/versions/node/v10.16.0/lib/node_modules/imba/lib/cli/imba.js:65:15)
    at Object.<anonymous> (/Users/ccscanf/.nvm/versions/node/v10.16.0/lib/node_modules/imba/bin/imba:6:28)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

## Example code

```
class x1
	def initialize
		@m = "m"

const x = x1.new

console.log "x",x
```

**Comment by shiv-1998** [comment]
I would like to work on this issue.

**Comment by scanf** [comment]
@shiv-1998 how is it going?

**Comment by JulienMLan** [comment]
@scanf If it is cool with you I would like to take a stab at this, Will post an update in at most 1 week.
