### ISSUE TITLE
Not working on Windows

### ISSUE THREAD

**Issue by altteo** [imba/imba#302]
Because of the paths.

**Comment by altteo** [comment]
Problems are with rollup too, not only compiler.

**Comment by scanf** [comment]
Here is the error message I see when building on Windows
```
PS C:\Users\scanf\src\github.com\imba\template> npm run build

> @ build C:\Users\scanf\src\github.com\imba\template
> imba-rollup

internal/modules/cjs/loader.js:611
    throw err;
    ^

Error: Cannot find module 'C:\Users\scanf\src\github.com\imba\template\node_modules\imba\index.js/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
    at Function.Module._load (internal/modules/cjs/loader.js:535:25)
    at Module.require (internal/modules/cjs/loader.js:663:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at resolveImba (C:\Users\scanf\src\github.com\imba\template\node_modules\imba-rollup\dist\bin.js:156:13)
    at Object.<anonymous> (C:\Users\scanf\src\github.com\imba\template\node_modules\imba-rollup\dist\bin.js:162:14)
    at Module._compile (internal/modules/cjs/loader.js:734:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:745:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:566:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `imba-rollup`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\scanf\AppData\Roaming\npm-cache\_logs\2020-02-20T21_28_13_479Z-debug.log
```

**Comment by scanf** [comment]
So instead of using string concatenation we should rely on manipulating paths via the paths module. I can try to fix this tomorrow morning.

**Comment by altteo** [comment]
Rollup easy to fix. The problem is with compiler.

**Comment by somebee** [comment]
This should be an easy fix in the compiler as well.

**Comment by scanf** [comment]
Resolved in https://github.com/imba/imba/commit/541cdb55e22fb08194ed2d8ae8c11394ca5d99b7
