### ISSUE TITLE
v2: SSR not working again

### ISSUE THREAD

**Issue by scanf** [imba/imba#336]
I remember this working but I keep seeing `imba is not defined`

```
$ yarn run imba examples/no-tag.imba
yarn run v1.22.4
$ /Users/scanf/src/github.com/scanf/server-side-imba/node_modules/.bin/imba examples/no-tag.imba
/Users/scanf/src/github.com/scanf/server-side-imba/examples/no-tag.imba:2
let data = (($t$0=imba.createElement('h1',0,null,null,"This is a Heading!",null)),
           ^

ReferenceError: imba is not defined
    at Object.<anonymous> (/Users/scanf/src/github.com/scanf/server-side-imba/examples/no-tag.imba:2:12)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at run (/Users/scanf/src/github.com/imba/imba/bin/imba:47:15)
    at main (/Users/scanf/src/github.com/imba/imba/bin/imba:98:9)
    at Object.<anonymous> (/Users/scanf/src/github.com/imba/imba/bin/imba:101:1)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

```imba
let data = <h1> "This is a Heading!"
console.log(data)
console.log(data.toString())
```

**Comment by scanf** [comment]
Ideally you would run the imba command and it would just work (like it does in v1).
