### ISSUE TITLE
Upgrading issues from v2.0.0-alpha.58 to v2.0.0-alpha.68

### ISSUE THREAD

**Issue by scanf** [imba/imba#387]
Hei

TLDR: When I upgrade to v2.0.0-alpha.68 my project stops building, see below build error. The culprit line is propably this thing
```
      <p #user-font-size css:font-size="{fontSize}px"> "a A あ　ア　万"
```

I am currently stuck at Imba v2.0.0-alpha.58 since upgrading to the latest breaks my project notion2Anki https://github.com/alemayhu/notion2anki

I am not doing things in a clean way of course but would prefer to not rewrite it all at once since I have actual users who are relying on it working. They are mostly medicine students and have exams to pass 😅

```
➜ git clone https://github.com/alemayhu/notion2anki
➜ cd notion2Anki
➜ yarn build
yarn run v1.22.4
$ imba build.imba
skipping make_pages
$ /Users/scanf/src/github.com/alemayhu/notion2anki/node_modules/.bin/webpack --mode=production

error compiling upload-page.imba

Hash: 8652f9a0e7369c21d9b8
Version: webpack 4.43.0
Time: 3939ms
Built at: 07/10/2020 3:07:24 PM
 2 assets
Entrypoint main = app.js app.css
[0] multi ./src/app.imba ./src/app.css 40 bytes {0} [built]
[2] (webpack)/buildin/global.js 472 bytes {0} [built]
[3] ./src/upload-page.imba 1.54 KiB {0} [built] [failed] [2 errors]
[4] ./src/app.imba + 13 modules 49.3 KiB {0} [built]
    | ./src/app.imba 3.17 KiB [built]
    |     + 13 hidden modules
[5] ./src/app.css 41 bytes [built]
[6] ./node_modules/postcss-loader/src??postcss!./src/app.css 1.89 MiB [built]
    + 3 hidden modules

ERROR in ./src/upload-page.imba
Module Error (from ./node_modules/imba/loader.js):
Parse error at [835:8]: Unexpected 'CSSIDENTIFIER'
      24 | 						<div .text-center>
      25 | 							<h2> "Font size: {fontSize}"
   -> 26 | 							<input[fontSize] name="font-size" min='20' type="range" :change.fontSizeChanged(fontSize)>
      27 | 							<p #user-font-size css:font-size="{fontSize}px"> "a A あ　ア　万"
      28 | 						<button :click .text-4xl .font-bold .text-white .n2a-blue-bg .rounded-full .px-8 .py-2 type="submit"> "Download"
 @ ./src/app.imba 9:0-23
 @ multi ./src/app.imba ./src/app.css

ERROR in ./src/upload-page.imba
Module build failed: Error: Final loader (./node_modules/imba/loader.js) didn't return a Buffer or String
    at /Users/scanf/src/github.com/alemayhu/notion2anki/node_modules/webpack/lib/NormalModule.js:333:18
    at /Users/scanf/src/github.com/alemayhu/notion2anki/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/scanf/src/github.com/alemayhu/notion2anki/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/scanf/src/github.com/alemayhu/notion2anki/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/scanf/src/github.com/alemayhu/notion2anki/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/Users/scanf/src/github.com/alemayhu/notion2anki/node_modules/loader-runner/lib/LoaderRunner.js:124:12)
    at iterateNormalLoaders (/Users/scanf/src/github.com/alemayhu/notion2anki/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/scanf/src/github.com/alemayhu/notion2anki/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/scanf/src/github.com/alemayhu/notion2anki/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/scanf/src/github.com/alemayhu/notion2anki/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/scanf/src/github.com/alemayhu/notion2anki/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
 @ ./src/app.imba 9:0-23
 @ multi ./src/app.imba ./src/app.css
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/postcss-loader/src/index.js??postcss!src/app.css:
    Entrypoint undefined = extract-text-webpack-plugin-output-filename
    [0] ./node_modules/postcss-loader/src??postcss!./src/app.css 1.89 MiB {0} [built]

error Command failed with exit code 2.

(node:65643) UnhandledPromiseRejectionWarning: [object Uint8Array]
(Use `node --trace-warnings ...` to show where the warning was created)
(node:65643) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:65643) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

✨  Done in 5.31s.

```

**Comment by scanf** [comment]
Sorry, my bad. I was not trying hard enough 😄 Using the new syntax for databinding resolves this. Should be better documented @somebee , I just noticed it while looking closer at the applications in the examples.

```
+                                                       <input$fontSize name="font-size" min='20' type="range">
+                                                       <p css:font-size="{$fontSize}px"> "a A あ　ア　万"
```
