### ISSUE TITLE
Parcel doesn't seem to work with imbav2?

### ISSUE THREAD

**Issue by illogikal** [imba/imba#471]
### Details

I upgraded a new project I started with start-imba and then I updated the version of imba from 1.5.2 to v2.0.0-alpha.100. 

### Expected Behavior

Keeps working.

### Actual Behavior

[4:33:28 PM]: Server running at http://localhost:1234 
[4:33:28 PM]: Building...
[4:33:28 PM]: Building index.html...
[4:33:28 PM]: Building index.css...
[4:33:28 PM]: Building index.imba...
[4:33:28 PM]: Building css-loader.js...
[4:33:28 PM]: 🚨  APP_ROOT/imba/source/index.imba: Cannot use import statement outside a module
[4:33:28 PM]: (function (exports, require, module, __filename, __dirname) { import './core'
                                                              ^^^^^^

SyntaxError: Cannot use import statement outside a module
    at new Script (vm.js:100:7)
    at NativeCompileCache._moduleCompile (APP_ROOT/imba/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (APP_ROOT/imba/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (APP_ROOT/imba/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (APP_ROOT/imba/node_modules/imba/index.js:4:1)
    at Module._compile (APP_ROOT/imba/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
[4:33:29 PM]: Built ../node_modules/parcel-bundler/src/builtins/bundle-url.js...
[4:33:29 PM]: Built ../node_modules/parcel-bundler/src/builtins/css-loader.js...
[4:33:29 PM]: Built components/app.css...
[4:33:29 PM]: Built index.css...
[4:36:18 PM]: Building package.json...
[4:36:18 PM]: Building...
[4:36:18 PM]: Building css-loader.js...
[4:36:18 PM]: Building index.css...
[4:36:18 PM]: Building bundle-url.js...
[4:36:18 PM]: Building app.css...
[4:36:18 PM]: Built ../node_modules/parcel-bundler/src/builtins/css-loader.js...
[4:36:18 PM]: Built ../node_modules/parcel-bundler/src/builtins/bundle-url.js...
[4:36:18 PM]: Built index.css...
[4:36:18 PM]: Built components/app.css...
[4:36:18 PM]: Producing bundles...
[4:36:18 PM]: Packaging...
[4:36:18 PM]: ✨  Built in 90ms.
[4:36:26 PM]: Request: http://localhost:1234/
[4:36:26 PM]: Request: http://localhost:1234/bca1542f88ef8253c16b452e9ad09f98.css
[4:36:26 PM]: Request: http://localhost:1234/9395ef18b1a0b3b467bbd1525b0e00ee.js
[4:36:26 PM]: Request: http://localhost:1234/favicon.ico
[4:36:48 PM]: Request: http://localhost:1234/

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Windows 10, node.js 8.1):
- Operating System and version (Mac or Linux):
- Useful link to screenshot or any other information:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by somebee** [comment]
Well, there are a lot of breaking changes going from imba 1 to imba 2, so upgrading an imba app like this is sadly not feasible at this point. I'm pretty sure that's the reason. start-imba is certainly not updated for it yet :/
