### ISSUE TITLE
Local server is crashing in alpha.133

### ISSUE THREAD

**Issue by ericvida** [imba/imba#541]
To reproduce: 
start a new proẹct with `npx imba create app`
replace code within client.imba with the code below.
start server witih `npm start`
reload browser to see server crash.

```
const dictionary = [
	title: "title"
	info: [
		one: "one"
		---
		two: "two"
		---
		three: [
			text: "three"
		]
	]
	---
	title: "title"
	info: [
		one: "one"
		---
		two: "two"
		---
		three: [
			text: "three"
		]
	]
]
global css html
	ff:sans
console.log dictionary # this causes live server to crash. The error is not very specific. Once I refresh browser, the server will crash.
tag app
	def render
		<self> "hello world!!"
			for item in dictionary
				<h1> item.title
imba.mount <app>
```

ERROR: 
```
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/__assets__//app//client.BRDSD7S9.js.map'
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:147:14
    at FSReqCallback.oncomplete (fs.js:171:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/__assets__//app//client.BRDSD7S9.js.map'
}
× server.imba: exited with error code: 1
✔ compile app/client.imba browser in 11ms v
ℹ building in /var/folders/ps/zz5q44bs6_56k1n5l06_7c2m0000gn/T/tmp-37452-wXh4e2S7mH2j
✔ write public/index.html 0.5kb
✔ write public/__assets__/app/client.MCJVAEDG.js.map 51.4kb
✔ write public/__assets__/app/client.MCJVAEDG.js 33.7kb
✔ write server.js.manifest 14.9kb
ℹ server.imba: errorerd
✔ write server.loader.js 9.3kb
```

**Comment by ericvida** [comment]
I cannot consistently reproduce this error myself. So I will close for now.
