### ISSUE TITLE
Global object `Intl` crashes Imba server

### ISSUE THREAD

**Issue by ericvida** [imba/imba#546]
Just the use of the Intl global object, causes a crash in the server to me.

## Error
```
listening on http://localhost:3000/
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/__assets__//app//client.SNDGZZSD.js.map'
Emitted 'error' event on ReadStream instance at:
    at internal/fs/streams.js:147:14
    at FSReqCallback.oncomplete (fs.js:171:23) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/__assets__//app//client.SNDGZZSD.js.map'
}
× server.imba: exited with error code: 1
```

## Offending Code
```
global css html
	ff:sans
let input = "ដេរកេច្បារម្លូចាស់គិតប្រាំឈ្លោះដើមរកម្ដាយជ្រូក"
let segmenter = new Intl.Segmenter('kh', granularity: 'word')
let segmented = segmenter(input)
console.log segmented
# output should match monosyl below.
let monosyl = ["ដេរ", "កេ", "ច្បារ", "ម្លូ", "ចាស់", "គិត", "ប្រាំ", "ឈ្លោះ", "ដើម", "រក", "ម្ដាយ", "ជ្រូក"]
tag app
	css span c@odd:red5 c@even:purple5 fs:13 pr:5
	css .wordlike
		c:blue5
	def render
		<self> "hello!"
imba.mount <app>
```

**Comment by ericvida** [comment]
It seems that it's supported only in certain browsers.
Should the result be that the server crashes?
I think the only error that should be encountered is in the console.

**Comment by ericvida** [comment]
@somebee 
Here is a repo with the issue: https://github.com/ericvida/imba-crash-localhost-intl
I have a screen recording of me reproducing the problem here: https://discord.com/channels/682180555286380545/806112312570150944/849276328234844160
