### ISSUE TITLE
Build error 

### ISSUE THREAD

**Issue by Pistus** [imba/imba#565]
Getting this error when trying to deploy scrimba-site `pricing-page` branch commit `740f517` on staging. The commit works locally.

Staging node version: v16.3.0

```
> build
> imba build -m src/server.imba

 > node_modules/imba/bin/imba.imba.js:16183:27: error: [imba] Cannot read property 'map' of undefined
    16183 │         errors: res.errors.map(function(_0) {
          ╵                            ^
    at /home/scrimba/apps/scrimba-site/node_modules/imba/bin/imba.imba.js:16183:28
    at async callback (/home/scrimba/apps/scrimba-site/node_modules/esbuild/lib/main.js:772:28)
    at async handleRequest (/home/scrimba/apps/scrimba-site/node_modules/esbuild/lib/main.js:603:30)

   node_modules/imba/bin/imba.imba.js:16167:15: note: This error came from the "onLoad" callback registered here
    16167 │     return esb.onLoad({filter: /\.imba1?$/}, async function({path...
          ╵                ~~~~~~
    at Bundle.plugin (/home/scrimba/apps/scrimba-site/node_modules/imba/bin/imba.imba.js:16167:16)
    at handlePlugins (/home/scrimba/apps/scrimba-site/node_modules/esbuild/lib/main.js:686:7)
    at Object.buildOrServe (/home/scrimba/apps/scrimba-site/node_modules/esbuild/lib/main.js:903:44)
    at /home/scrimba/apps/scrimba-site/node_modules/esbuild/lib/main.js:1444:17
    at new Promise (<anonymous>)
    at Object.build (/home/scrimba/apps/scrimba-site/node_modules/esbuild/lib/main.js:1443:14)
    at Object.build (/home/scrimba/apps/scrimba-site/node_modules/esbuild/lib/main.js:1334:51)
    at /home/scrimba/apps/scrimba-site/node_modules/imba/bin/imba.imba.js:16216:41
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

   src/server.imba:64:7: note: The plugin "imba" was triggered by this import
       64 │ import './pages/pricing'/*$path$*/;
          ╵        ~~~~~~~~~~~~~~~~~

^[[31m×^[[39m failed with 1 errors [
  {
    detail: TypeError: Cannot read property 'map' of undefined
        at /home/scrimba/apps/scrimba-site/node_modules/imba/bin/imba.imba.js:16183:28
        at async callback (/home/scrimba/apps/scrimba-site/node_modules/esbuild/lib/main.js:772:28)
        at async handleRequest (/home/scrimba/apps/scrimba-site/node_modules/esbuild/lib/main.js:603:30),
    location: {
      column: 27,
      file: 'node_modules/imba/bin/imba.imba.js',
      length: 0,
      line: 16183,
      lineText: '        errors: res.errors.map(function(_0) {\n' +
        '    at /home/scrimba/apps/scrimba-site/node_modules/imba/bin/imba.imba.js:16183:28\n' +
        '    at async callback (/home/scrimba/apps/scrimba-site/node_modules/esbuild/lib/main.js:772:28)\n' +
        '    at async handleRequest (/home/scrimba/apps/scrimba-site/node_modules/esbuild/lib/main.js:603:30)',
      namespace: 'file'
    },
    notes: [ [Object], [Object] ],
    text: "[imba] Cannot read property 'map' of undefined"
  }
]
```

**Comment by Pistus** [comment]
Downgraded node to 14.17.1 and it works
