### ISSUE TITLE
Is it even possible to run Imba 1+sass on recent node, or is it over?

### ISSUE THREAD

**Issue by taw** [imba/imba#650]
I created a lot of Imba 1 miniapps like https://github.com/taw/imba-rotn

The issue is the same so let's just take this one:

* if I try to install it with original package-lock.json that used to work, it crashes with node-gyp error
* if I accept dependabot's upgrades, it builds, then crashes at runtime with this:

```
npm run dev

> imba-rotn@1.0.0 dev
> webpack-dev-server --mode=development --content-base dist/

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/taw/github/imba-rotn/dist
✖ ｢wdm｣: Hash: 1e1bc4f00000e002f556
Version: webpack 4.33.0
Time: 1468ms
Built at: 14/02/2022 01:27:31
 Asset     Size  Chunks             Chunk Names
app.js  468 KiB    main  [emitted]  main
Entrypoint main = app.js
[1] multi (webpack)-dev-server/client?http://localhost ./src/app.imba ./src/app.scss 52 bytes {main} [built]
[./node_modules/ansi-html/index.js] 4.16 KiB {main} [built]
[./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/app.scss] ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/app.scss 360 bytes [built] [failed] [1 error]
[./node_modules/imba/imba.imba] 51 bytes {main} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {main} [built]
[./node_modules/style-loader/lib/addStyles.js] 10.2 KiB [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost] (webpack)-dev-server/client?http://localhost 4.29 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.59 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.04 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.77 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {main} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.63 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {main} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./src/app.imba] 1.9 KiB {main} [built]
    + 36 hidden modules

ERROR in ./src/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Node Sass version 7.0.0 is incompatible with ^4.0.0.
    at getRenderFuncFromSassImpl (/Users/taw/github/imba-rotn/node_modules/sass-loader/lib/loader.js:108:19)
    at Object.sassLoader (/Users/taw/github/imba-rotn/node_modules/sass-loader/lib/loader.js:46:20)
    at /Users/taw/github/imba-rotn/node_modules/webpack/lib/NormalModule.js:302:20
    at /Users/taw/github/imba-rotn/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /Users/taw/github/imba-rotn/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at runSyncOrAsync (/Users/taw/github/imba-rotn/node_modules/loader-runner/lib/LoaderRunner.js:143:3)
    at iterateNormalLoaders (/Users/taw/github/imba-rotn/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at /Users/taw/github/imba-rotn/node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at /Users/taw/github/imba-rotn/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:73:15
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
 @ ./src/app.scss

ERROR in ./src/app.scss (./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/app.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Node Sass version 7.0.0 is incompatible with ^4.0.0.
    at getRenderFuncFromSassImpl (/Users/taw/github/imba-rotn/node_modules/sass-loader/lib/loader.js:108:19)
    at Object.sassLoader (/Users/taw/github/imba-rotn/node_modules/sass-loader/lib/loader.js:46:20)
 @ ./src/app.scss 2:14-115
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js!node_modules/sass-loader/lib/loader.js!src/app.scss:
    Entrypoint undefined = extract-text-webpack-plugin-output-filename
    [./node_modules/css-loader/index.js!./node_modules/sass-loader/lib/loader.js!./src/app.scss] ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/app.scss 360 bytes {0} [built] [failed] [1 error]

    ERROR in ./src/app.scss (./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/app.scss)
    Module build failed (from ./node_modules/sass-loader/lib/loader.js):
    Error: Node Sass version 7.0.0 is incompatible with ^4.0.0.
        at getRenderFuncFromSassImpl (/Users/taw/github/imba-rotn/node_modules/sass-loader/lib/loader.js:108:19)
        at Object.sassLoader (/Users/taw/github/imba-rotn/node_modules/sass-loader/lib/loader.js:46:20)
ℹ ｢wdm｣: Failed to compile.
```

So basically what's the situation:

* imba 1 is so dead, none of this will ever run again?
* imba 1 with scss is totally dead, but it would run if I removed scss and just used plain css for these?
* it would run, but only if I keep old version of node forever
* there's some package.json fix for this problem?

I tried some package.json fixes, but so far I've been unable to make any progress.

There's no automated way to upgrade these to Imba 2, so I need to fix them, or all that code is lost forever.

(older React apps suffer from the same node-sass issue, in their case `npm install --save --save-exact react-scripts@5.0.0` works)

**Comment by somebee** [comment]
Hmm. So there is a sass version that works on later node I presume? Is this related to the webpack-dev-server or inherently an issue with Imba itself? Sounds like something that should be possible to fix. I still have a few large-ish imba1 codebases running. We should definitely make sure they can at least still run :/

**Comment by taw** [comment]
I think this is something about webpack (and css-loader and other dependencies) used by Imba1, not Imba1 itself, as old CreateReactApp+Sass projects are also affected by the same issue.

[This is one such CreateReactApp-based project, and somewhere in package-lock.json in this commit are the relevant fixes](https://github.com/taw/hoi4/commit/a176c10de42cf5fc9984678d6311e8740d142ff5).

For newest node the recommended Sass version is the `sass` package (it's pure-JS), not `node-sass` package (which links to C libsass and causes these compatibility issues, as node C API is just so unstable).

The situation:

* node-sass (old version) - won't even compile on latest node; I think it should work if you downgrade node
* node-sass (latest version; still deprecated) - will compile, but css-loader crashes due to API changes
* sass - nothing to compile, but css-loader crashes due to API changes - I suspect switching to this will avoid any further such issues in the future, as it's pure-JS

**Comment by taw** [comment]
[So I finally figured out how to restore old Imba 1 + SCSS projects and documented changes in this blog post](https://dev.to/taw/upgrading-old-imba-1-apps-to-run-on-modern-node-jf7).
