### ISSUE TITLE
ERR_REQUIRE_ESM when importing a pure ESM package (lowdb)

### ISSUE THREAD

**Issue by TaliNation** [imba/imba#662]
### Details

When importing a pure ESM package like [lowdb](https://github.com/typicode/lowdb), I get the following error message :

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: <path>\esm-issue\node_modules\lowdb\lib\index.js
require() of ES modules is not supported.
require() of <path>\esm-issue\node_modules\lowdb\lib\index.js from <path>\esm-issue\server.imba is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from <path>\esm-issue\node_modules\lowdb\package.json.
```

I tried to follow the [provided gist](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c), but I still get the error no matter what.

### My Environment

- Windows 10
- Node v14.17.5 (also tried on v16.14.2)
- Imba v2.0.0-alpha.205
- lowdb v3.0.0

### Steps to Reproduce

1. Create a sample project : `npx imba create esm-issue`
2. Install lowdb : `npm install lowdb`
3. Import lowdb in server.imba : `import * as lowdb from 'lowdb'`

Optionnal :

- Add `"type": "module"` in package.json

### Stack Trace

```
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1089:13)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (<path>\esm-issue\server.imba:3:19)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.G.d.Module._extensions.<computed> (<path>\esm-issue\node_modules\imba\loader.imba.js:1:4875)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by MexHigh** [comment]
Same problem here with `node-fetch`
