### ISSUE TITLE
[Bug] Imba throws Symlink error on Windows

### ISSUE THREAD

**Issue by IRod22** [imba/imba#768]
### Description

I was trying to boot up the imba.io docs server, and I expected the server to boot up. Instead, I got this ugly error message:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@jest/expect-utils@29.2.2',
npm WARN EBADENGINE   required: { node: '^14.15.0 || ^16.10.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.7.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@jest/schemas@29.0.0',
npm WARN EBADENGINE   required: { node: '^14.15.0 || ^16.10.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.7.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@jest/types@29.2.1',
npm WARN EBADENGINE   required: { node: '^14.15.0 || ^16.10.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.7.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'pretty-format@29.2.1',
npm WARN EBADENGINE   required: { node: '^14.15.0 || ^16.10.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.7.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'diff-sequences@29.2.0',
npm WARN EBADENGINE   required: { node: '^14.15.0 || ^16.10.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.7.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'expect@29.2.2',
npm WARN EBADENGINE   required: { node: '^14.15.0 || ^16.10.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.7.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'jest-diff@29.2.1',
npm WARN EBADENGINE   required: { node: '^14.15.0 || ^16.10.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.7.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'pretty-format@29.2.1',
npm WARN EBADENGINE   required: { node: '^14.15.0 || ^16.10.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.7.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'jest-get-type@29.2.0',
npm WARN EBADENGINE   required: { node: '^14.15.0 || ^16.10.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.7.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'jest-matcher-utils@29.2.2',
npm WARN EBADENGINE   required: { node: '^14.15.0 || ^16.10.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.7.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'pretty-format@29.2.1',
npm WARN EBADENGINE   required: { node: '^14.15.0 || ^16.10.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.7.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'jest-message-util@29.2.1',
npm WARN EBADENGINE   required: { node: '^14.15.0 || ^16.10.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.7.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'pretty-format@29.2.1',
npm WARN EBADENGINE   required: { node: '^14.15.0 || ^16.10.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.7.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'jest-util@29.2.1',
npm WARN EBADENGINE   required: { node: '^14.15.0 || ^16.10.0 || >=18.0.0' },
npm WARN EBADENGINE   current: { node: 'v17.8.0', npm: '8.7.0' }
npm WARN EBADENGINE }

up to date, audited 300 packages in 12s

73 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> imba.io@1.0.0 build
> npm run build-content && npm run build-api-docs && imba build index.imba


> imba.io@1.0.0 build-content
> imba scripts/build-content.imba

error here Error: EPERM: operation not permitted, symlink 'C:\Users\Robotics\imba\imba.io\node_modules' -> 'C:\Users\Robotics\AppData\Local\Temp\tmp-1968-wIERrm3Vx0Wd\node_modules'
    at Object.symlinkSync (node:fs:1668:3)
    at De.write (C:\Users\Robotics\imba\imba.io\node_modules\imba\bin\imba.imba.js:172:2634)
    at C:\Users\Robotics\imba\imba.io\node_modules\imba\bin\imba.imba.js:169:768
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  errno: -4048,
  syscall: 'symlink',
  code: 'EPERM',
  path: 'C:\\Users\\Robotics\\imba\\imba.io\\node_modules',
  dest: 'C:\\Users\\Robotics\\AppData\\Local\\Temp\\tmp-1968-wIERrm3Vx0Wd\\node_modules'
}
Error: Cannot find module 'marked'
Require stack:
- C:\Users\Robotics\AppData\Local\Temp\tmp-1968-wIERrm3Vx0Wd\build-content.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at renderer (C:\Users\Robotics\imba\imba.io\src\util\markdown.imba:1:16)
    at C:\Users\Robotics\AppData\Local\Temp\tmp-1968-wIERrm3Vx0Wd\build-content.js:9:59
    at Object.<anonymous> (C:\Users\Robotics\imba\imba.io\scripts\build-content.imba:7:10)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Robotics\\AppData\\Local\\Temp\\tmp-1968-wIERrm3Vx0Wd\\build-content.js'
  ]
}

Node.js v17.8.0 
```

Run the command below to reproduce the issue.

### Reproduction

```cmd
npx imba create test-throw && cd test-throw && npm i && npm run build
```

### System Environment

```text
System:
    OS: Windows 10 10.0.19043
    CPU: (2) x64 Intel(R) Celeron(R) CPU  N3060  @ 1.60GHz
    Memory: 1.02 GB / 3.91 GB
  Binaries:
    Node: 17.8.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.7.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (107.0.1418.35)
    Internet Explorer: 11.0.19041.1566
  npmPackages:
    imba: ^2.0.0-alpha.223 => 2.0.0-alpha.225
```

**Comment by IRod22** [comment]
This was originally discovered in imba/imba.io#262.

**Comment by haikyuu** [comment]
@IRod22 can you try to fix the issue by investigatin? none of Imba's maintainers have a windows machine unfortunately. That would be very helpful if you could.

The warnings can go if you use node 16 or 18. And maybe that fixes the issue as well

**Comment by IRod22** [comment]
OK, @haikyuu. I'm installing `nvs` right now, so I can try the LTS version (v18 LTS),

Also, has the core team tried using GitHub Actions? Actions can test Imba as if it were on a Windows machine.

**Comment by IRod22** [comment]
I got the following from my console; the `npm WARN` warnings went away, but I still have the same error when running `npm run build`.
Note that I removed the output for when `nvs` was downloading the required binaries.
```cmd
> nvs lts npm i && nvs lts npm run build

----------------------
npm i (v18.12.1)      
----------------------

up to date, audited 300 packages in 13s

73 packages are looking for funding
  run `npm fund` for details       

found 0 vulnerabilities

======================
Success (1)
======================

----------------------
npm run build (v18.12.1)
----------------------  

> imba.io@1.0.0 build
> npm run build-content && npm run build-api-docs && imba build index.imba


> imba.io@1.0.0 build-content    
> imba scripts/build-content.imba

error here Error: EPERM: operation not permitted, symlink 'C:\Users\Robotics\imba\imba.io\node_modules' -> 'C:\Users\Robotics\AppData\Local\Temp\tmp-8544-8U43DUxQYIyz\node_modules'
    at Object.symlinkSync (node:fs:1713:3)
    at De.write (C:\Users\Robotics\imba\imba.io\node_modules\imba\bin\imba.imba.js:172:2634)
    at C:\Users\Robotics\imba\imba.io\node_modules\imba\bin\imba.imba.js:169:768
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4048,
  syscall: 'symlink',
  code: 'EPERM',
  path: 'C:\\Users\\Robotics\\imba\\imba.io\\node_modules',
  dest: 'C:\\Users\\Robotics\\AppData\\Local\\Temp\\tmp-8544-8U43DUxQYIyz\\node_modules'
}
node:internal/modules/cjs/loader:998
  throw err;
  ^

Error: Cannot find module 'marked'
Require stack:
- C:\Users\Robotics\AppData\Local\Temp\tmp-8544-8U43DUxQYIyz\build-content.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Module._load (node:internal/modules/cjs/loader:841:27)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at renderer (C:\Users\Robotics\imba\imba.io\src\util\markdown.imba:1:16)
    at C:\Users\Robotics\AppData\Local\Temp\tmp-8544-8U43DUxQYIyz\build-content.js:9:59
    at Object.<anonymous> (C:\Users\Robotics\imba\imba.io\scripts\build-content.imba:7:10)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Robotics\\AppData\\Local\\Temp\\tmp-8544-8U43DUxQYIyz\\build-content.js'
  ]
}

Node.js v18.12.1

======================
Errors (1)
v18.12.1 Error: Non-zero exit code: 1
======================
```

**Comment by IRod22** [comment]
@haikyuu Sorry I am just getting back to this, but has the Imba team considered using a test workflow using `windows-latest`? The team could only have it run on the hotfix branch and any feature branches, so the organization will not use up its action limit. I can write a workflow for the team and open a pull request if y'all would like for me to do so; I would just need to know what branch to target before doing this.

**Comment by IRod22** [comment]
@haikyuu I found the issue in nodejs/node#18518. The only way to fix this is to either be on development mode, run `npx imba` as administrator, or create file symlinks for all of the individual files. I'm going to comment on the other issue that there's still a bug on node v18 LTS and see what's going on. I'll keep this issue posted when I hear updates.

**Comment by haikyuu** [comment]
Thank you @IRod22
We do have e2e tests running on windows. But no maintainer is a windows user daily

**Comment by IRod22** [comment]
> Thank you @IRod22
> We do have e2e tests running on windows. But no maintainer is a windows user daily

You're welcome, @haikyuu. I wish I could help, but I would have to get to know Imba's internals, and I would not have the time to maintain Imba anyway.

**Comment by IRod22** [comment]
@haikyuu, may I ask where `De.write()` is defined at? If a solution turns up, I want to be able to know where the buggy code is, so I can test it to see if Imba works after the fix. According to the call stack, the error is where `De.write()` is calling `fs.symlinkSync()`, which is causing the error.

**Comment by haikyuu** [comment]
@IRod22 What node version are you using? You seem to be using 17 which is not an LTS version.
Try using an LTS version like 18. I suspect that will fix the issue. I wouldn't personally recommend debugging that deep as things should just work ™️

**Comment by IRod22** [comment]
@haikyuu Here's my node version:
```ps1
> node -v
v18.12.1
```

**Comment by IRod22** [comment]
I just reran the npm scripts and the same error occurs. :thinking:

**Comment by haikyuu** [comment]
I'd say this is not a bug in Imba itself. Rather a bug in https://github.com/imba/imba.io build script.
Sorry for the redirect (again) @IRod22

**Comment by IRod22** [comment]
@haikyuu IIRC I am the admin of the entire computer, but I'll need to check.

**Comment by IRod22** [comment]
@haikyuu this just keeps getting weirder and weirder the more I look into this IMO. My reasoning is that if I am administrator, I should not have this issue. Do you know of anyone on the Imba Discord server who could reproduce or has reproduced this on Windows 10 with Node v18? I think we'll need some more help with this. I would look into a PR right now, but I have my hands tied.

**Comment by familyfriendlymikey** [comment]
@IRod22 You have to specifically launch your terminal as administrator. I recently set up my windows machine and am able to reproduce this issue. Running the terminal as administrator solved it. I'll look into nfs.symlinkSync and see what's causing the issue specifically. I can at least implement a better error message.

**Comment by familyfriendlymikey** [comment]
Turning on "developer mode" in Windows system settings works for me without having to run a terminal as admin. Until we find an actual solution, I'll update the catch for that symlink code to mention the setting. I wonder how Vite and `npm link` do it without that.

**Comment by IRod22** [comment]
@familyfriendlymikey have you tried asking the Vite team in their [discussions area](https://github.com/vitejs/vite/discussions)?
